-- =============================================================================
-- Migration 000001: Initial Schema
-- Tori — Subscriptions & Recurring Billing Engine
-- =============================================================================
-- Design rules enforced throughout:
--   • All monetary amounts stored as BIGINT in kobo (smallest NGN unit). No floats.
--   • Every tenant-scoped table has tenant_id as a non-nullable column.
--   • ledger_entries is structurally immutable — no updated_at column.
--   • UUIDs generated by PostgreSQL via gen_random_uuid().
--   • All timestamps are TIMESTAMPTZ (timezone-aware).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Tenants
-- SaaS businesses registered on the billing engine.
-- ---------------------------------------------------------------------------
CREATE TABLE tenants (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT        NOT NULL,
  email            TEXT        UNIQUE NOT NULL,
  api_key_hash     TEXT        NOT NULL,
  -- bcrypt hash of the API key. Plaintext never stored, never logged.
  webhook_secret   TEXT        NOT NULL,
  dunning_config   JSONB       NOT NULL DEFAULT '{}',
  -- Per-tenant dunning overrides. Falls back to system defaults when empty.
  -- Schema: { retry_intervals_days: [3,7,14,21], max_attempts: 4,
  --           suspension_action: "suspend", notify_customer: true,
  --           notify_merchant: true, smart_retry: true }
  is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Customers
-- End users of each tenant's product.
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           UUID        NOT NULL REFERENCES tenants(id),
  external_id         TEXT,
  -- Tenant's own customer ID for correlation. Queryable via Platform API.
  email               TEXT        NOT NULL,
  name                TEXT,
  nomba_customer_id   TEXT,
  tokenised_card      JSONB,
  -- Encrypted token reference from Nomba checkout. Never raw card data.
  metadata            JSONB,
  is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
  -- Soft delete only. Hard delete would corrupt ledger FK references.
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id, email)
);

-- ---------------------------------------------------------------------------
-- Plans
-- Billing plan definitions owned by a tenant.
-- ---------------------------------------------------------------------------
CREATE TABLE plans (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID        NOT NULL REFERENCES tenants(id),
  name             TEXT        NOT NULL,
  description      TEXT,
  amount           BIGINT      NOT NULL CHECK (amount > 0),
  -- Kobo. Must be positive. Zero-amount plans not supported.
  currency         TEXT        NOT NULL DEFAULT 'NGN',
  interval         TEXT        NOT NULL CHECK (interval IN ('monthly', 'annual', 'custom')),
  interval_count   INTEGER     NOT NULL DEFAULT 1 CHECK (interval_count > 0),
  trial_period_days INTEGER    NOT NULL DEFAULT 0 CHECK (trial_period_days >= 0),
  is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
  metadata         JSONB,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Subscriptions
-- The core billing relationship between a customer and a plan.
-- ---------------------------------------------------------------------------
CREATE TABLE subscriptions (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID        NOT NULL REFERENCES tenants(id),
  customer_id           UUID        NOT NULL REFERENCES customers(id),
  plan_id               UUID        NOT NULL REFERENCES plans(id),
  status                TEXT        NOT NULL CHECK (status IN (
                          'TRIALING', 'ACTIVE', 'PAST_DUE', 'DUNNING',
                          'PAUSED', 'SUSPENDED', 'CANCELLED'
                        )),
  current_period_start  TIMESTAMPTZ NOT NULL,
  current_period_end    TIMESTAMPTZ NOT NULL,
  trial_end             TIMESTAMPTZ,
  paused_at             TIMESTAMPTZ,
  cancelled_at          TIMESTAMPTZ,
  cancel_at_period_end  BOOLEAN     NOT NULL DEFAULT FALSE,
  dunning_attempt       INTEGER     NOT NULL DEFAULT 0,
  next_retry_at         TIMESTAMPTZ,
  idempotency_key       TEXT        UNIQUE,
  metadata              JSONB,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Invoices
-- Generated before every charge attempt. Source of billing history.
-- ---------------------------------------------------------------------------
CREATE TABLE invoices (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID        NOT NULL REFERENCES tenants(id),
  subscription_id   UUID        NOT NULL REFERENCES subscriptions(id),
  customer_id       UUID        NOT NULL REFERENCES customers(id),
  amount            BIGINT      NOT NULL CHECK (amount >= 0),
  -- Kobo. Zero allowed for trial-start audit invoices.
  currency          TEXT        NOT NULL DEFAULT 'NGN',
  status            TEXT        NOT NULL CHECK (status IN (
                      'draft', 'open', 'paid', 'void', 'uncollectible'
                    )),
  due_date          TIMESTAMPTZ NOT NULL,
  paid_at           TIMESTAMPTZ,
  nomba_charge_ref  TEXT,
  proration_details JSONB,
  line_items        JSONB       NOT NULL,
  idempotency_key   TEXT        UNIQUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Ledger Entries
-- Append-only financial event log. This is the source of truth.
--
-- IMMUTABILITY CONTRACT:
--   • NO updated_at column — this table has no update path.
--   • NO soft delete — is_deleted does not exist on this table.
--   • The repository layer exposes NO Update or Delete methods.
--   • Any modification to a ledger entry is a bug, not a feature.
--   • Corrections are made by writing a new ADJUSTMENT entry.
-- ---------------------------------------------------------------------------
CREATE TABLE ledger_entries (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID        NOT NULL REFERENCES tenants(id),
  subscription_id  UUID        REFERENCES subscriptions(id),
  invoice_id       UUID        REFERENCES invoices(id),
  customer_id      UUID        REFERENCES customers(id),
  entry_type       TEXT        NOT NULL CHECK (entry_type IN (
                     'CHARGE', 'REFUND', 'CREDIT', 'PRORATION',
                     'ADJUSTMENT', 'OVERRIDE', 'TRIAL_START', 'TRIAL_END'
                   )),
  -- OVERRIDE: written when an admin manually force-sets subscription state.
  -- Requires a reason field in the metadata JSONB.
  direction        TEXT        NOT NULL CHECK (direction IN ('DEBIT', 'CREDIT')),
  amount           BIGINT      NOT NULL CHECK (amount >= 0),
  -- Kobo. Always non-negative. Direction encodes sign.
  -- Zero allowed for TRIAL_START and TRIAL_END audit markers.
  currency         TEXT        NOT NULL DEFAULT 'NGN',
  description      TEXT        NOT NULL,
  idempotency_key  TEXT        UNIQUE NOT NULL,
  metadata         JSONB,
  -- For OVERRIDE entries: metadata must include { "reason": "..." }
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- NO updated_at. This table is structurally immutable.
);

-- ---------------------------------------------------------------------------
-- Scheduled Jobs
-- PostgreSQL-backed durable job queue.
-- Jobs survive process restarts. No Redis dependency for durability.
-- Workers claim jobs via SELECT FOR UPDATE SKIP LOCKED.
-- ---------------------------------------------------------------------------
CREATE TABLE scheduled_jobs (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    UUID        REFERENCES tenants(id),
  -- Nullable: system-level jobs (stale lock cleanup) have no tenant.
  job_type     TEXT        NOT NULL,
  -- process_billing_cycle | retry_failed_payment | expire_trial |
  -- deliver_webhook | send_dunning_notification |
  -- suspend_subscription | reactivate_subscription
  payload      JSONB       NOT NULL,
  status       TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN (
                 'pending', 'processing', 'done', 'failed'
               )),
  scheduled_at TIMESTAMPTZ NOT NULL,
  locked_at    TIMESTAMPTZ,
  locked_by    TEXT,
  -- Worker instance UUID. Set when status = 'processing'.
  attempts     INTEGER     NOT NULL DEFAULT 0,
  max_attempts INTEGER     NOT NULL DEFAULT 5,
  last_error   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Webhook Endpoints
-- Tenant-registered outbound delivery targets.
-- ---------------------------------------------------------------------------
CREATE TABLE webhook_endpoints (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   UUID        NOT NULL REFERENCES tenants(id),
  url         TEXT        NOT NULL,
  events      TEXT[]      NOT NULL,
  -- Subscribed event types. Empty array = no events delivered.
  secret      TEXT        NOT NULL,
  -- Used for HMAC-SHA256 signing. Never returned in API responses after creation.
  api_version TEXT        NOT NULL DEFAULT '2026-06-01',
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Webhook Deliveries
-- Full delivery audit log. Every attempt recorded regardless of outcome.
-- ---------------------------------------------------------------------------
CREATE TABLE webhook_deliveries (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint_id     UUID        NOT NULL REFERENCES webhook_endpoints(id),
  tenant_id       UUID        NOT NULL REFERENCES tenants(id),
  event_type      TEXT        NOT NULL,
  api_version     TEXT        NOT NULL,
  payload         JSONB       NOT NULL,
  status          TEXT        NOT NULL CHECK (status IN (
                    'pending', 'delivered', 'failed'
                  )),
  response_status INTEGER,
  response_body   TEXT,
  attempt_count   INTEGER     NOT NULL DEFAULT 0,
  next_retry_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- Indexes
-- Defined after all tables to avoid forward reference issues.
-- Every index is justified by a specific query pattern.
-- =============================================================================

-- Subscriptions: tenant + status filtering (most common dashboard query)
CREATE INDEX idx_subscriptions_tenant_status
  ON subscriptions(tenant_id, status);

-- Subscriptions: dunning retry scheduler — find DUNNING/PAST_DUE due for retry
CREATE INDEX idx_subscriptions_next_retry
  ON subscriptions(next_retry_at)
  WHERE status IN ('DUNNING', 'PAST_DUE');

-- Subscriptions: billing clock — find ACTIVE subs whose period has ended
CREATE INDEX idx_subscriptions_period_end
  ON subscriptions(current_period_end)
  WHERE status = 'ACTIVE';

-- Subscriptions: TRIALING subs due for trial expiry check
CREATE INDEX idx_subscriptions_trial_end
  ON subscriptions(trial_end)
  WHERE status = 'TRIALING';

-- Scheduled jobs: worker claim query — pending jobs ordered by scheduled_at
CREATE INDEX idx_scheduled_jobs_pending
  ON scheduled_jobs(scheduled_at, id)
  WHERE status = 'pending';

-- Ledger: tenant-scoped time-range queries (revenue reports, MRR)
CREATE INDEX idx_ledger_tenant_created
  ON ledger_entries(tenant_id, created_at);

-- Ledger: subscription-scoped history (subscription detail page)
CREATE INDEX idx_ledger_subscription
  ON ledger_entries(subscription_id, created_at);

-- Invoices: subscription billing history
CREATE INDEX idx_invoices_subscription
  ON invoices(subscription_id);

-- Invoices: tenant-scoped status filtering
CREATE INDEX idx_invoices_tenant_status
  ON invoices(tenant_id, status);

-- Webhook deliveries: retry queue — failed deliveries due for retry
CREATE INDEX idx_webhook_deliveries_retry
  ON webhook_deliveries(status, next_retry_at)
  WHERE status = 'failed';

-- Customers: external_id lookup (Platform API: GET /customers?external_id=...)
CREATE INDEX idx_customers_tenant_external
  ON customers(tenant_id, external_id)
  WHERE external_id IS NOT NULL;

-- Customers: exclude soft-deleted from all standard queries
CREATE INDEX idx_customers_active
  ON customers(tenant_id)
  WHERE is_deleted = FALSE;

-- Plans: active plans per tenant
CREATE INDEX idx_plans_tenant_active
  ON plans(tenant_id)
  WHERE is_active = TRUE;
