export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string; id: string }
  | { type: "h3"; text: string }
  | { type: "code"; lang?: string; code: string }
  | { type: "callout"; variant?: "info" | "warn" | "success"; text: string }
  | { type: "table"; headers: string[]; rows: string[][] }
  | { type: "list"; items: string[] };

export type Section = { id: string; label: string; icon: string; blocks: Block[] };
export type Group = { group: string; items: Section[] };
export type Tab = { id: string; label: string; groups: Group[] };

const BASE = "https://api.tori.ng";

export const TABS: Tab[] = [
  {
    id: "documentation",
    label: "Documentation",
    groups: [
      {
        group: "Introduction",
        items: [
          {
            id: "welcome",
            label: "Welcome to Tori",
            icon: "ti-hand-stop",
            blocks: [
              { type: "p", text: "Tori is a subscription billing engine built natively on Nomba's payment infrastructure. It solves one specific problem: every Nigerian SaaS, edtech, and creator platform that charges customers on a recurring basis has had to build the same billing system from scratch. Subscriptions, payment retries, access control, revenue reporting — all of it, rebuilt by every team, every time." },
              { type: "p", text: "Tori is that system. Built once, running on Nomba's rails, available to every business that needs it." },
              { type: "callout", variant: "success", text: "You can test the full API right now with no account. Try creating a plan, customer, and subscription in the sandbox without signing up." },
              { type: "h2", text: "What Tori does", id: "what" },
              { type: "p", text: "When you integrate Tori, three things happen. You make three API calls to set up a subscription. After that, Tori handles everything else automatically for as long as the subscription is active." },
              { type: "list", items: [
                "Tori charges the customer through Nomba on each billing cycle — monthly, annual, or a custom interval you define",
                "When a charge fails, Tori classifies the reason and decides whether to retry, and when",
                "Every attempt, success, failure, refund, and credit is written to an immutable ledger you can audit at any time",
                "Your product receives a webhook event for every billing action so you can react — suspend access, send a receipt, restore service",
                "Your dashboard shows MRR, churn rate, dunning recovery, and net revenue computed from real data",
              ]},
              { type: "h2", text: "What Tori does not do", id: "what-not" },
              { type: "p", text: "Tori is not a payment processor. It does not move money directly. Nomba moves the money. Tori is the orchestration layer that decides when to charge, what to do when it fails, and how to record what happened. Think of Nomba as the engine and Tori as the transmission — you interact with Tori, and Tori talks to Nomba on your behalf." },
              { type: "h2", text: "The three objects", id: "objects" },
              { type: "p", text: "Everything in Tori is built around three core objects. Once you understand these three things, the entire system makes sense." },
              { type: "table", headers: ["Object", "What it represents", "Example"], rows: [
                ["Plan", "A pricing template — what you charge and how often", "₦15,000/month with a 14-day free trial"],
                ["Customer", "A person or business that pays you", "amaka@startup.ng, mapped to your own user ID"],
                ["Subscription", "The live billing relationship between a customer and a plan", "Amaka on the Pro plan, currently ACTIVE"],
              ]},
              { type: "p", text: "You create a plan once. You create a customer when someone signs up. You create a subscription to link the two. That is the entire setup. Everything else — charging, retrying, reporting — happens automatically." },
            ],
          },
        ],
      },
      {
        group: "Getting Started",
        items: [
          {
            id: "keys",
            label: "Obtain API keys",
            icon: "ti-key",
            blocks: [
              { type: "p", text: "Every call to the Platform API must include your secret API key. This key is how Tori knows which account is making the request and which customers and plans belong to that account." },
              { type: "p", text: "You receive your key automatically when you create a Tori account. It is shown exactly once — on the screen immediately after signup. If you miss it, you will need to rotate the key and get a new one." },
              { type: "callout", variant: "warn", text: "Your API key is shown only once. Copy it into a password manager or secret storage system immediately. Tori stores only a hash of the key and cannot show it to you again. If you lose it, rotate it from the dashboard — the old key stops working immediately." },
              { type: "h2", text: "What the key looks like", id: "format" },
              { type: "p", text: "Live keys always start with `tori_live_` followed by a UUID. This prefix makes it easy to identify and helps you avoid accidentally committing keys to source control." },
              { type: "code", lang: "bash", code: "tori_live_3f9a2c71-8b4e-4d2a-9c1f-7e5d8a0b6c34" },
              { type: "h2", text: "How to use it", id: "using" },
              { type: "p", text: "Add your key to every Platform API request in the `X-API-Key` header. There is no OAuth flow, no token exchange — just the key in the header, and the request authenticates." },
              { type: "code", lang: "bash", code: `curl ${BASE}/v1/platform/plans \\\n  -H "X-API-Key: tori_live_..." \\\n  -H "Content-Type: application/json"` },
              { type: "h2", text: "Keeping it secret", id: "secret" },
              { type: "p", text: "Your API key should only exist in two places: your secret manager, and your backend server's environment variables. It should never be in your frontend code, your mobile app, a public GitHub repository, or sent to a user's browser. Anyone who has your key can create subscriptions, access customer data, and read your financial records." },
              { type: "callout", variant: "info", text: "The dashboard uses a separate JWT-based authentication system precisely so your secret API key never has to touch a browser. The Platform API key is for your server. The dashboard is for your team." },
              { type: "h2", text: "Rotating your key", id: "rotating" },
              { type: "p", text: "If you suspect your key has been compromised, rotate it immediately from the dashboard under API Keys. When you rotate, Tori generates a new key and the old one stops working at that exact moment. Deploy the new key to your server before rotating if you want to avoid any downtime." },
            ],
          },
          {
            id: "auth",
            label: "Authenticate",
            icon: "ti-lock",
            blocks: [
              { type: "p", text: "Tori has two separate authentication systems. They exist for different purposes and you will use both — one for your server code, one for your team's dashboard access." },
              { type: "h2", text: "Platform API — for your server", id: "platform-auth" },
              { type: "p", text: "Your backend code uses the secret API key in the `X-API-Key` header. This is the authentication method for creating customers, starting subscriptions, and reading billing data programmatically. It is a simple, stateless header — no sessions, no tokens, no expiry." },
              { type: "code", lang: "bash", code: `curl ${BASE}/v1/platform/subscriptions \\\n  -H "X-API-Key: tori_live_..." \\\n  -d '{ "customer_id": "cus_...", "plan_id": "plan_..." }'` },
              { type: "h2", text: "Dashboard API — for your team", id: "dashboard-auth" },
              { type: "p", text: "When you log into the Tori dashboard, you receive a short-lived JWT access token. This token is used for dashboard API calls — viewing subscriptions, reading metrics, managing webhooks. It expires after 15 minutes, at which point it is exchanged for a new one using the refresh token." },
              { type: "code", lang: "bash", code: `POST ${BASE}/v1/auth/login\n{ "email": "you@business.ng", "password": "your-password" }\n\n# Response\n{\n  "data": {\n    "access_token": "eyJ...",\n    "refresh_token": "eyJ...",\n    "token_type": "Bearer"\n  }\n}` },
              { type: "p", text: "Pass the access token in the `Authorization: Bearer` header on dashboard API calls." },
              { type: "table", headers: ["Auth method", "Header", "Where to use", "Expires"], rows: [
                ["API key", "X-API-Key: tori_live_...", "Your server backend", "Never (until rotated)"],
                ["JWT access token", "Authorization: Bearer eyJ...", "Dashboard API calls", "15 minutes"],
                ["Refresh token", "POST /v1/auth/refresh", "Get a new access token", "7 days"],
              ]},
              { type: "callout", variant: "warn", text: "Never use the JWT access token from your server code, and never put the secret API key in browser code. The separation exists deliberately — your API key has full account access and must stay server-side only." },
            ],
          },
          {
            id: "first",
            label: "First integration",
            icon: "ti-rocket",
            blocks: [
              { type: "p", text: "This page walks through the complete happy path — from nothing to a live, billing subscription — with every request and response shown. Follow these steps in order and you will have working recurring billing in under an hour." },
              { type: "callout", variant: "info", text: "All amounts in Tori are in kobo — the smallest unit of the Naira. ₦15,000 is 1500000 kobo. This eliminates floating point errors in financial calculations. Always send and receive amounts in kobo." },
              { type: "h2", text: "Step 1 — Create a plan", id: "step-1" },
              { type: "p", text: "A plan defines what you charge and how often. Create one plan for each pricing tier you offer. Plans are reusable — one plan can have thousands of subscribers." },
              { type: "code", lang: "bash", code: `curl ${BASE}/v1/platform/plans \\\n  -H "X-API-Key: tori_live_..." \\\n  -H "Content-Type: application/json" \\\n  -d '{\n    "name": "Pro",\n    "amount": 1500000,\n    "interval": "monthly",\n    "trial_period_days": 14\n  }'` },
              { type: "code", lang: "json", code: `{\n  "data": {\n    "id": "plan_8f3a2c71-...",\n    "name": "Pro",\n    "amount": 1500000,\n    "currency": "NGN",\n    "interval": "monthly",\n    "interval_count": 1,\n    "trial_period_days": 14,\n    "is_active": true\n  }\n}` },
              { type: "p", text: "Save the `id` from the response. You will use it when creating subscriptions." },
              { type: "h2", text: "Step 2 — Create a customer", id: "step-2" },
              { type: "p", text: "When a user signs up on your product, create a matching customer in Tori. The `external_id` field is your own identifier for this user — typically your database user ID. Tori keeps it so you can always find the right customer without storing Tori's IDs in your database." },
              { type: "code", lang: "bash", code: `curl ${BASE}/v1/platform/customers \\\n  -H "X-API-Key: tori_live_..." \\\n  -H "Content-Type: application/json" \\\n  -d '{\n    "email": "amaka@startup.ng",\n    "name": "Amaka Obi",\n    "external_id": "user_12345"\n  }'` },
              { type: "code", lang: "json", code: `{\n  "data": {\n    "id": "cus_9b4e7d21-...",\n    "email": "amaka@startup.ng",\n    "name": "Amaka Obi",\n    "external_id": "user_12345"\n  }\n}` },
              { type: "h2", text: "Step 3 — Start a subscription", id: "step-3" },
              { type: "p", text: "Link the customer to the plan. This single call starts the billing relationship. If the plan has a trial period, the subscription starts in TRIALING state and no charge is attempted until the trial ends. If there is no trial, the subscription starts ACTIVE and the first charge happens immediately." },
              { type: "code", lang: "bash", code: `curl ${BASE}/v1/platform/subscriptions \\\n  -H "X-API-Key: tori_live_..." \\\n  -H "Content-Type: application/json" \\\n  -d '{\n    "customer_id": "cus_9b4e7d21-...",\n    "plan_id": "plan_8f3a2c71-...",\n    "idempotency_key": "signup_user_12345"\n  }'` },
              { type: "code", lang: "json", code: `{\n  "data": {\n    "id": "sub_2b71c4e9-...",\n    "status": "TRIALING",\n    "current_period_start": "2026-06-20T00:00:00Z",\n    "current_period_end": "2026-07-04T00:00:00Z"\n  }\n}` },
              { type: "callout", variant: "success", text: "That is the complete setup. Tori now manages this customer's billing indefinitely. The next charge attempts automatically when the trial ends. You do not need to do anything else unless you want to cancel, pause, or change the subscription." },
              { type: "h2", text: "Step 4 — Listen for webhooks", id: "step-4" },
              { type: "p", text: "Register a webhook endpoint so Tori can notify your product when billing events happen. Your product listens for these events and reacts — for example, by unlocking access when a subscription activates, or restricting access when a payment fails." },
              { type: "code", lang: "bash", code: `curl ${BASE}/v1/webhooks/endpoints \\\n  -H "Authorization: Bearer eyJ..." \\\n  -H "Content-Type: application/json" \\\n  -d '{\n    "url": "https://yourapp.ng/webhooks/tori",\n    "events": ["*"]\n  }'` },
              { type: "p", text: "The response includes a `secret`. Save it immediately — it is never shown again. You use it to verify that webhook deliveries are genuinely from Tori and not from a third party." },
              { type: "h2", text: "Step 5 — React to events in your product", id: "step-5" },
              { type: "p", text: "Your webhook handler receives events and updates your product accordingly. Here is what a minimal handler looks like:" },
              { type: "code", lang: "js", code: `app.post('/webhooks/tori', (req, res) => {\n  // Always verify the signature first\n  const sig = req.headers['tori-signature'];\n  if (!verifySignature(req.body, sig, process.env.TORI_WEBHOOK_SECRET)) {\n    return res.status(401).send('Invalid signature');\n  }\n\n  const event = req.body;\n\n  switch (event.type) {\n    case 'subscription.activated':\n      // Unlock full access for this customer\n      await db.users.update({ toriCustomerId: event.customer_id }, { access: 'full' });\n      break;\n\n    case 'payment.failed':\n      // Show payment warning, restrict some features\n      await db.users.update({ toriCustomerId: event.customer_id }, { access: 'restricted' });\n      break;\n\n    case 'dunning.recovered':\n      // Payment came through on a retry — restore access\n      await db.users.update({ toriCustomerId: event.customer_id }, { access: 'full' });\n      break;\n\n    case 'subscription.cancelled':\n      // Customer cancelled — offboard gracefully\n      await offboardCustomer(event.customer_id);\n      break;\n  }\n\n  // Always respond 200 quickly, do work asynchronously\n  res.status(200).send('ok');\n});` },
            ],
          },
        ],
      },
      {
        group: "Core Concepts",
        items: [
          {
            id: "plans",
            label: "Plans & pricing",
            icon: "ti-file-text",
            blocks: [
              { type: "p", text: "A plan is a pricing template. It defines three things: how much you charge, how often you charge it, and whether new subscribers get a free trial. Plans are reusable — you create a plan once and any number of customers can subscribe to it." },
              { type: "p", text: "Plans are separate from subscriptions deliberately. If you change the price on a plan, existing subscribers are not affected — they stay on what they signed up for. New subscribers get the new price. This is the correct behaviour for subscription businesses: you honour the price your customer agreed to." },
              { type: "h2", text: "Billing intervals", id: "intervals" },
              { type: "p", text: "Tori supports three billing intervals. Monthly and annual are self-explanatory. Custom is for anything else — school fees charged every 120 days, quarterly retainers, bimonthly memberships." },
              { type: "table", headers: ["Interval", "When the customer is charged", "When to use it"], rows: [
                ["monthly", "Once per calendar month", "Most SaaS products, memberships, subscriptions"],
                ["annual", "Once per year", "Annual plans with a discount vs monthly"],
                ["custom", "Every N days you specify", "Termly fees, quarterly billing, non-standard cycles"],
              ]},
              { type: "callout", variant: "info", text: "Month-end billing is handled correctly. A subscription that starts on January 31 renews on February 28 (or 29 in a leap year), then March 31. It never skips a month or drift to an earlier date over time. This is a surprisingly common bug in custom billing implementations." },
              { type: "h2", text: "Trial periods", id: "trials" },
              { type: "p", text: "Set `trial_period_days` to give new subscribers a free trial. During the trial, the subscription is in `TRIALING` state and no charge is attempted. When the trial ends, Tori automatically transitions the subscription to `ACTIVE` and runs the first charge." },
              { type: "p", text: "Trial boundaries are recorded in the ledger as `TRIAL_START` and `TRIAL_END` entries, so your reporting clearly shows which revenue came from converted trials." },
              { type: "h2", text: "Full plan object", id: "object" },
              { type: "code", lang: "json", code: `{\n  "id": "plan_8f3a2c71-...",\n  "name": "Pro",\n  "amount": 1500000,\n  "currency": "NGN",\n  "interval": "monthly",\n  "interval_count": 1,\n  "trial_period_days": 14,\n  "is_active": true,\n  "created_at": "2026-06-01T00:00:00Z"\n}` },
              { type: "h2", text: "Deactivating a plan", id: "deactivate" },
              { type: "p", text: "Deactivating a plan stops new subscriptions from using it. Existing subscribers on that plan keep billing normally — deactivation does not cancel any subscriptions. Use this when you retire an old pricing tier." },
            ],
          },
          {
            id: "subs",
            label: "Subscriptions",
            icon: "ti-refresh",
            blocks: [
              { type: "p", text: "A subscription is the live billing relationship between one customer and one plan. It is the central object in Tori — everything else exists to support it. A subscription has a status that changes over time based on payment outcomes and deliberate actions." },
              { type: "h2", text: "The subscription lifecycle", id: "lifecycle" },
              { type: "p", text: "When you create a subscription, it starts in one of two states depending on whether the plan has a trial: `TRIALING` if there is a trial period, `ACTIVE` immediately if not. From there, the status changes automatically based on what happens with payments, or deliberately when you or the customer takes an action." },
              { type: "h2", text: "Reading a subscription", id: "reading" },
              { type: "code", lang: "json", code: `{\n  "id": "sub_2b71c4e9-...",\n  "customer_id": "cus_9b4e7d21-...",\n  "plan_id": "plan_8f3a2c71-...",\n  "status": "DUNNING",\n  "current_period_start": "2026-06-01T00:00:00Z",\n  "current_period_end": "2026-07-01T00:00:00Z",\n  "dunning_attempt": 2,\n  "next_retry_at": "2026-06-27T00:00:00Z"\n}` },
              { type: "p", text: "`dunning_attempt` tells you how many retries have been made on the current failed cycle. If it is 0, the subscription is current. If it is greater than 0, a payment failed and retries are in progress. `next_retry_at` tells you when the next retry will be attempted." },
              { type: "h2", text: "Taking actions on a subscription", id: "actions" },
              { type: "p", text: "You can take three deliberate actions on a subscription: pause, resume, or cancel. Each is a simple POST request." },
              { type: "table", headers: ["Action", "What it does", "Can it be undone?"], rows: [
                ["Pause", "Stops billing temporarily. The subscription record is kept. The customer retains access if your product allows it.", "Yes — resume restarts billing"],
                ["Resume", "Restarts billing from a paused state. The next charge happens on the next normal billing cycle.", "N/A"],
                ["Cancel", "Permanently ends the subscription. No more charges. The record remains for auditing.", "No — cancellation is final"],
              ]},
              { type: "callout", variant: "warn", text: "Cancellation is permanent and enforced at the state machine level. A cancelled subscription cannot be reactivated. If a customer wants to come back after cancelling, create a new subscription for them. This prevents accidental reactivations and keeps your billing history clean." },
              { type: "h2", text: "Idempotent creation", id: "idempotent" },
              { type: "p", text: "Always pass an `idempotency_key` when creating subscriptions. If your server retries the request due to a network timeout, the same key returns the original subscription instead of creating a duplicate. Use something unique per signup attempt — for example, your own user ID combined with the plan ID." },
              { type: "code", lang: "json", code: `{\n  "customer_id": "cus_...",\n  "plan_id": "plan_...",\n  "idempotency_key": "sub_user_12345_pro_plan"\n}` },
            ],
          },
          {
            id: "states",
            label: "The state machine",
            icon: "ti-arrows-shuffle",
            blocks: [
              { type: "p", text: "Every subscription is always in exactly one of seven states. Tori enforces this with a pure state machine — before any status change happens, the machine checks whether that transition is valid. If it is not, the request returns an error and nothing changes. This makes the system predictable: you can never end up in an impossible or inconsistent state." },
              { type: "h2", text: "The seven states", id: "seven-states" },
              { type: "table", headers: ["State", "What it means", "Billing happening?"], rows: [
                ["TRIALING", "The customer is in a free trial. No charge has been attempted yet.", "No"],
                ["ACTIVE", "The subscription is healthy. The customer is being charged on each cycle.", "Yes"],
                ["PAST_DUE", "A charge failed. The subscription is in a short grace period before dunning begins.", "Paused"],
                ["DUNNING", "Tori is actively retrying a failed payment on a schedule.", "Retrying"],
                ["PAUSED", "Billing has been deliberately suspended by you or the customer.", "No"],
                ["SUSPENDED", "All dunning retries were exhausted and the payment was never recovered.", "No"],
                ["CANCELLED", "The subscription has been permanently ended.", "No"],
              ]},
              { type: "h2", text: "How states change", id: "transitions" },
              { type: "p", text: "Most state changes happen automatically based on payment outcomes. A few are triggered by deliberate actions." },
              { type: "table", headers: ["From state", "What triggers the change", "New state"], rows: [
                ["TRIALING", "Trial period ends", "ACTIVE"],
                ["ACTIVE", "A charge fails", "PAST_DUE"],
                ["PAST_DUE", "Grace period ends", "DUNNING"],
                ["DUNNING", "A retry succeeds", "ACTIVE"],
                ["DUNNING", "All retries exhausted", "SUSPENDED"],
                ["ACTIVE", "You or customer calls /pause", "PAUSED"],
                ["PAUSED", "You or customer calls /resume", "ACTIVE"],
                ["Any (except CANCELLED)", "You or customer calls /cancel", "CANCELLED"],
              ]},
              { type: "callout", variant: "success", text: "Because the state machine validates every transition, you will never accidentally charge a cancelled subscription, resume a subscription that was never paused, or end up in a state that does not make logical sense. The 28 unit tests covering the state machine ensure this behaviour is correct." },
              { type: "h2", text: "What to do in your product for each state", id: "product-states" },
              { type: "table", headers: ["State", "Recommended product behaviour"], rows: [
                ["TRIALING", "Full access. Show how many trial days remain."],
                ["ACTIVE", "Full access. Nothing special needed."],
                ["PAST_DUE", "Full access or soft restriction. Show a gentle payment warning."],
                ["DUNNING", "Restricted access. Show a clear payment failure message with a way to update the card."],
                ["PAUSED", "Restricted or suspended access depending on your product."],
                ["SUSPENDED", "Suspend access. Offer the customer a way to restart their subscription."],
                ["CANCELLED", "Revoke access. Offer a way to create a new subscription if they want to return."],
              ]},
            ],
          },
          {
            id: "dunning",
            label: "Dunning & retries",
            icon: "ti-clock",
            blocks: [
              { type: "p", text: "Dunning is the process of recovering failed payments. When a subscription charge fails, Tori does not immediately give up. It classifies the failure, decides whether retrying makes sense, and schedules retries at the right times." },
              { type: "p", text: "This matters enormously in Nigeria. A significant percentage of recurring payment failures are not because the customer cannot or will not pay. Cards get blocked for online transactions. Banks have outages. Salaries arrive on the 25th. A naive billing system that retries immediately and then gives up loses all of that recoverable revenue." },
              { type: "h2", text: "How failure classification works", id: "classification" },
              { type: "p", text: "When a charge fails, Tori reads the failure code returned by Nomba and classifies it as either retriable or permanent." },
              { type: "table", headers: ["Failure type", "Examples", "What Tori does"], rows: [
                ["Retriable", "insufficient_funds, issuer_unavailable, transaction_timeout", "Schedules a retry according to the dunning schedule"],
                ["Permanent", "card_expired, card_blocked, do_not_honour", "Stops retrying immediately and moves to notifying the customer"],
              ]},
              { type: "callout", variant: "info", text: "Nigerian-specific: many cards are issued with online transactions blocked by default. The bank returns a code that looks like a temporary failure but will never succeed. Tori treats these as permanent so you do not burn four retry slots — and four Nomba transaction fees — on a charge that has no chance of going through." },
              { type: "h2", text: "The retry schedule", id: "retry-schedule" },
              { type: "p", text: "For retriable failures, Tori spaces retries to maximise recovery. The default schedule retries on Day 3, Day 7, Day 14, and Day 21 after the first failure. This spacing is deliberate — it covers multiple payday windows for customers paid weekly, biweekly, or at month-end." },
              { type: "table", headers: ["Attempt", "Days after first failure", "Why this timing"], rows: [
                ["Attempt 1", "Day 3", "Early retry catches short-term issues like temporary bank outages"],
                ["Attempt 2", "Day 7", "Covers customers paid weekly"],
                ["Attempt 3", "Day 14", "Covers biweekly salary cycles"],
                ["Attempt 4", "Day 21", "Final attempt before suspension, covers late-month salaries"],
              ]},
              { type: "p", text: "After the fourth attempt, if the payment has still not succeeded, the subscription moves to `SUSPENDED`. The customer retains their data but loses access until they update their payment method and restart the subscription." },
              { type: "h2", text: "What dunning recovery means in money", id: "money" },
              { type: "p", text: "If your product has 500 active subscribers at ₦10,000/month, and 8% of charges fail in a given month, that is ₦400,000 at risk. Without intelligent dunning, much of that is lost. With Tori's payday-aware retry schedule and Nigerian failure classification, a substantial share of those failures resolve on their own — often because funds simply became available after payday." },
              { type: "h2", text: "Dunning configuration", id: "config" },
              { type: "p", text: "The dunning schedule, maximum retry count, and what happens after retries are exhausted (suspend vs cancel) are all configurable per tenant in your settings. You can also configure whether Tori sends email notifications to the customer or just to you when dunning starts." },
            ],
          },
          {
            id: "ledger",
            label: "The ledger",
            icon: "ti-book",
            blocks: [
              { type: "p", text: "The Tori ledger is an append-only record of every financial event in your billing account. Every charge, refund, credit, proration, and adjustment writes one immutable row. Nothing is ever edited or deleted." },
              { type: "p", text: "This is not an accounting approximation. It is the authoritative source of truth for every naira that has ever moved through your billing system. Your MRR, churn, and revenue numbers are computed directly from this ledger." },
              { type: "h2", text: "Why append-only matters", id: "why" },
              { type: "p", text: "Most billing systems store a balance or a summary that gets updated whenever something changes. The problem is that if a bug causes a wrong update, you have no way to know what the correct number should be — the history is gone. The Tori ledger never updates existing rows. Every correction writes a new row. This means you can always reconstruct the full history of how any number was arrived at." },
              { type: "callout", variant: "success", text: "When an investor asks 'where does this ₦4.2M MRR number come from?', you can show them the exact 847 charge entries behind it, each with a timestamp, customer, and subscription reference. That is auditable financial history." },
              { type: "h2", text: "Entry types", id: "entries" },
              { type: "table", headers: ["Entry type", "When it's written", "Direction"], rows: [
                ["CHARGE", "A successful subscription charge went through", "DEBIT (money in)"],
                ["REFUND", "A refund was issued to a customer", "CREDIT (money out)"],
                ["CREDIT", "A manual credit was applied to a customer's account", "CREDIT"],
                ["PRORATION", "A mid-cycle plan change created a charge or credit", "DEBIT or CREDIT"],
                ["TRIAL_START", "A customer's trial period began", "Audit marker, zero amount"],
                ["TRIAL_END", "A customer's trial period ended", "Audit marker, zero amount"],
                ["OVERRIDE", "An admin made a manual correction, with a required reason", "DEBIT or CREDIT"],
              ]},
              { type: "h2", text: "Reading the ledger", id: "reading" },
              { type: "p", text: "You can query the ledger by date range, by customer, or by subscription. The summary endpoint gives you totals for any period." },
              { type: "code", lang: "bash", code: `GET ${BASE}/v1/ledger/summary?from=2026-06-01&to=2026-06-30\n\n{\n  "data": {\n    "total_charged": 42000000,\n    "total_refunded": 1500000,\n    "net_revenue": 40500000,\n    "entry_count": 312,\n    "currency": "NGN"\n  }\n}` },
            ],
          },
          {
            id: "webhooks-concept",
            label: "Webhooks",
            icon: "ti-webhook",
            blocks: [
              { type: "p", text: "Webhooks are how Tori tells your product what happened. When a subscription activates, a payment fails, a retry recovers a payment, or a customer cancels — Tori sends an HTTP POST request to your server with the event details. Your server processes the event and updates your product accordingly." },
              { type: "p", text: "Think of webhooks as the real-time communication channel between Tori and your product. Without webhooks, your product has no way to know when billing events happen unless it polls the API constantly. Webhooks are push-based — Tori notifies you the moment something happens." },
              { type: "h2", text: "The complete event list", id: "events" },
              { type: "table", headers: ["Event", "When it fires", "What your product should do"], rows: [
                ["subscription.activated", "Trial ends and first charge succeeds, or subscription starts with no trial", "Unlock full access"],
                ["subscription.paused", "You or the customer paused the subscription", "Restrict access as appropriate"],
                ["subscription.resumed", "You or the customer resumed a paused subscription", "Restore access"],
                ["subscription.cancelled", "The subscription was permanently cancelled", "Offboard the customer gracefully"],
                ["subscription.suspended", "All dunning retries were exhausted", "Suspend access, prompt the customer to update payment"],
                ["payment.succeeded", "A charge went through successfully", "Send a receipt, log the payment"],
                ["payment.failed", "A charge failed", "Show the customer a payment failure message"],
                ["payment.retrying", "A retry is scheduled after a failure", "Optionally notify the customer that you are retrying"],
                ["dunning.started", "The first retry has been scheduled", "Show a soft warning in your product"],
                ["dunning.recovered", "A retry charge succeeded after one or more failures", "Restore full access, send confirmation"],
                ["dunning.exhausted", "All retries failed, subscription moving to SUSPENDED", "Suspend access, send urgent notification"],
              ]},
              { type: "h2", text: "Verifying signatures", id: "verify" },
              { type: "p", text: "Every webhook delivery includes a `Tori-Signature` header containing an HMAC-SHA256 signature of the request body. Always verify this signature before processing the event. This ensures the request genuinely came from Tori and was not tampered with." },
              { type: "code", lang: "js", code: `const crypto = require('crypto');\n\nfunction verifySignature(rawBody, signature, secret) {\n  const expected = crypto\n    .createHmac('sha256', secret)\n    .update(rawBody)  // use the raw request body bytes\n    .digest('hex');\n\n  // Use timing-safe comparison to prevent timing attacks\n  return crypto.timingSafeEqual(\n    Buffer.from(expected),\n    Buffer.from(signature)\n  );\n}` },
              { type: "callout", variant: "warn", text: "Always respond with 200 immediately and process the event asynchronously. If your handler takes too long to respond, Tori treats it as a failure and schedules a retry. Duplicate events are possible — design your handler to be idempotent." },
            ],
          },
        ],
      },
      {
        group: "Nigerian Use Cases",
        items: [
          {
            id: "saas",
            label: "SaaS billing",
            icon: "ti-building-store",
            blocks: [
              { type: "p", text: "A Lagos SaaS startup charges ₦15,000/month for its Pro tier and ₦5,000/month for Starter. They have 300 customers and their engineering team has better things to do than maintain a billing system." },
              { type: "h2", text: "The setup", id: "saas-setup" },
              { type: "p", text: "They create two plans once. Every new user who completes signup gets a customer created in Tori and a subscription started automatically by their backend. New customers start on a 14-day trial. Tori handles the rest." },
              { type: "code", lang: "json", code: `// Create the Pro plan\n{ "name": "Pro", "amount": 1500000, "interval": "monthly", "trial_period_days": 14 }\n\n// Create the Starter plan\n{ "name": "Starter", "amount": 500000, "interval": "monthly", "trial_period_days": 7 }` },
              { type: "h2", text: "The webhook integration", id: "saas-webhooks" },
              { type: "p", text: "Their product listens for three events. `subscription.activated` unlocks the full product after the trial. `payment.failed` shows a banner and restricts certain features. `subscription.suspended` locks the account with a prompt to update their payment method." },
              { type: "p", text: "That is the entire billing integration. Their engineering team spent two days on it and have not touched it since." },
            ],
          },
          {
            id: "edtech",
            label: "Edtech termly fees",
            icon: "ti-school",
            blocks: [
              { type: "p", text: "An edtech platform charges school fees once per term — roughly every 120 days. Monthly billing does not match their business model. Annual billing would require parents to pay ₦150,000 upfront. They need termly billing." },
              { type: "h2", text: "The custom interval", id: "edtech-interval" },
              { type: "p", text: "Tori's `custom` interval handles this exactly. They create a plan with `interval: custom` and `interval_days: 120`. Every 120 days, Tori attempts the charge. If it fails — as it often does around school resumption — the dunning schedule gives them multiple retry windows aligned to when parents typically have funds." },
              { type: "code", lang: "json", code: `{\n  "name": "Term fees — SS2",\n  "amount": 5000000,\n  "interval": "custom",\n  "interval_days": 120\n}` },
              { type: "p", text: "The ledger gives the platform a clean record of every term's payment for every student, which they use for their own finance reconciliation at the end of each academic year." },
            ],
          },
          {
            id: "creator",
            label: "Creator subscriptions",
            icon: "ti-microphone",
            blocks: [
              { type: "p", text: "A creator sells a ₦2,500/month membership to 2,000 subscribers — exclusive content, early access, a private community. At this volume, the numbers are relentless: 160 failed charges every month if 8% fail, which at ₦2,500 each is ₦400,000 at risk." },
              { type: "h2", text: "Why dunning recovery matters here", id: "creator-dunning" },
              { type: "p", text: "At ₦2,500/charge, no creator is going to manually chase down 160 failed payments. They need the system to do it automatically. Tori's dunning engine retries each failed charge four times across a three-week window. For a creator audience, a significant portion of those failures clear after payday." },
              { type: "code", lang: "json", code: `{ "name": "Membership", "amount": 250000, "interval": "monthly" }` },
              { type: "p", text: "The customer portal is also important here. Creators handle a lot of billing support questions — 'I want to pause', 'I want to cancel', 'can I change my card'. Tori's portal token lets the creator's platform generate a self-service link for each member so they can manage their own subscription without contacting support." },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "api-reference",
    label: "API Reference",
    groups: [
      {
        group: "Reference",
        items: [
          {
            id: "ref-conventions",
            label: "Conventions",
            icon: "ti-adjustments",
            blocks: [
              { type: "p", text: "Tori's API follows consistent patterns across every endpoint. Learn them once and they apply everywhere." },
              { type: "h2", text: "Base URL", id: "base-url" },
              { type: "code", lang: "bash", code: `${BASE}` },
              { type: "h2", text: "Response envelope", id: "envelope" },
              { type: "p", text: "Every response is wrapped in the same envelope structure. Success responses have a `data` field. List responses add `pagination`. Every response has a `meta` field with a request ID and the API version." },
              { type: "code", lang: "json", code: `// Single object\n{\n  "data": { "id": "...", "...": "..." },\n  "meta": { "request_id": "01J...", "api_version": "2026-06-01" }\n}\n\n// List\n{\n  "data": [ { "id": "..." }, { "id": "..." } ],\n  "pagination": { "has_more": false, "total": 18 },\n  "meta": { "request_id": "01J...", "api_version": "2026-06-01" }\n}\n\n// Error\n{\n  "error": { "code": "not_found", "message": "the requested resource does not exist" },\n  "meta": { "request_id": "01J...", "api_version": "2026-06-01" }\n}` },
              { type: "h2", text: "Money is always in kobo", id: "money" },
              { type: "p", text: "Every amount field in the API is an integer representing kobo — the smallest unit of the Nigerian Naira. ₦15,000 is `1500000`. ₦2,500 is `250000`. There are no decimal amounts anywhere. This eliminates floating point rounding errors in financial calculations." },
              { type: "h2", text: "Dates are ISO 8601", id: "dates" },
              { type: "p", text: "All timestamps are in ISO 8601 format in UTC. `2026-06-20T00:00:00Z`. When filtering by date range, pass dates in `YYYY-MM-DD` format: `?from=2026-06-01&to=2026-06-30`." },
              { type: "h2", text: "Pagination", id: "pagination" },
              { type: "p", text: "List endpoints accept `limit` (max results per page, default 20) and `offset` (number of results to skip). The response includes `pagination.has_more` to tell you whether another page exists." },
              { type: "code", lang: "bash", code: `GET /v1/customers?limit=50&offset=100` },
              { type: "h2", text: "Request ID", id: "request-id" },
              { type: "p", text: "Every response includes `meta.request_id` — a unique identifier for that specific API call. Log this alongside your own application logs. When something goes wrong, quote the request ID in a support ticket and Tori can trace the exact call in the system logs." },
            ],
          },
          {
            id: "ref-plans",
            label: "Plans",
            icon: "ti-file-text",
            blocks: [
              { type: "h2", text: "Create a plan", id: "create" },
              { type: "code", lang: "bash", code: `POST /v1/platform/plans\n\n{\n  "name": "Pro",               // required\n  "amount": 1500000,           // required, in kobo\n  "currency": "NGN",           // optional, defaults to NGN\n  "interval": "monthly",       // optional: monthly, annual, custom. default monthly\n  "interval_count": 1,         // optional, for custom intervals\n  "trial_period_days": 14      // optional, 0 means no trial\n}` },
              { type: "h2", text: "List plans", id: "list" },
              { type: "code", lang: "bash", code: `GET /v1/plans` },
              { type: "h2", text: "Get a single plan", id: "get" },
              { type: "code", lang: "bash", code: `GET /v1/plans/{id}` },
              { type: "h2", text: "Update a plan", id: "update" },
              { type: "p", text: "You can update a plan's name, description, and amount. Updating the amount does not change what existing subscribers pay — it only affects new subscribers." },
              { type: "code", lang: "bash", code: `PATCH /v1/plans/{id}\n\n{\n  "name": "Pro (updated)",\n  "amount": 1800000\n}` },
              { type: "h2", text: "Deactivate a plan", id: "deactivate" },
              { type: "p", text: "Deactivating stops new subscriptions from using the plan. Existing subscriptions are unaffected." },
              { type: "code", lang: "bash", code: `DELETE /v1/plans/{id}` },
            ],
          },
          {
            id: "ref-customers",
            label: "Customers",
            icon: "ti-users",
            blocks: [
              { type: "h2", text: "Create a customer", id: "create" },
              { type: "code", lang: "bash", code: `POST /v1/platform/customers\n\n{\n  "email": "amaka@startup.ng",  // required\n  "name": "Amaka Obi",          // optional\n  "external_id": "user_12345"   // optional but recommended\n}` },
              { type: "p", text: "Pass `external_id` as your own identifier for this user. It lets you look up Tori customers by your own ID without storing Tori IDs in your database." },
              { type: "h2", text: "Look up by your own ID", id: "by-external" },
              { type: "code", lang: "bash", code: `GET /v1/customers?external_id=user_12345` },
              { type: "h2", text: "List customers", id: "list" },
              { type: "code", lang: "bash", code: `GET /v1/customers?limit=20&offset=0` },
              { type: "h2", text: "Update a customer", id: "update" },
              { type: "code", lang: "bash", code: `PATCH /v1/customers/{id}\n\n{ "name": "Amaka Obi-Johnson", "email": "new@startup.ng" }` },
              { type: "h2", text: "Archive a customer", id: "archive" },
              { type: "p", text: "Customers are never hard-deleted. Archiving soft-deletes them while preserving their full billing history in the ledger." },
              { type: "code", lang: "bash", code: `POST /v1/customers/{id}/archive` },
              { type: "h2", text: "Generate a portal token", id: "portal" },
              { type: "p", text: "Mint a short-lived token that lets the customer manage their own subscription in the self-service portal. Embed this link in your product so customers can cancel, pause, and view their invoices without contacting you." },
              { type: "code", lang: "bash", code: `GET /v1/platform/customers/{id}/portal-token\n\n{\n  "data": { "token": "eyJ...", "expires_in": "3600" }\n}` },
            ],
          },
          {
            id: "ref-subs",
            label: "Subscriptions",
            icon: "ti-refresh",
            blocks: [
              { type: "h2", text: "Create a subscription", id: "create" },
              { type: "code", lang: "bash", code: `POST /v1/platform/subscriptions\n\n{\n  "customer_id": "cus_...",             // required\n  "plan_id": "plan_...",               // required\n  "idempotency_key": "sub_user_12345"  // strongly recommended\n}` },
              { type: "h2", text: "List subscriptions", id: "list" },
              { type: "p", text: "Filter by status to see all subscriptions in a particular state — useful for finding everything in dunning or everything that needs attention." },
              { type: "code", lang: "bash", code: `GET /v1/subscriptions\nGET /v1/subscriptions?status=DUNNING\nGET /v1/subscriptions?status=ACTIVE&limit=50` },
              { type: "h2", text: "Get a single subscription", id: "get" },
              { type: "code", lang: "bash", code: `GET /v1/platform/subscriptions/{id}` },
              { type: "h2", text: "Cancel a subscription", id: "cancel" },
              { type: "code", lang: "bash", code: `POST /v1/platform/subscriptions/{id}/cancel` },
              { type: "h2", text: "Pause a subscription", id: "pause" },
              { type: "code", lang: "bash", code: `POST /v1/platform/subscriptions/{id}/pause` },
              { type: "h2", text: "Resume a subscription", id: "resume" },
              { type: "code", lang: "bash", code: `POST /v1/platform/subscriptions/{id}/resume` },
              { type: "callout", variant: "info", text: "Every lifecycle action is validated against the state machine. If the action is not valid from the current state — for example, trying to pause a cancelled subscription — you receive 422 invalid_transition and nothing changes." },
            ],
          },
          {
            id: "ref-ledger",
            label: "Ledger",
            icon: "ti-book",
            blocks: [
              { type: "h2", text: "List ledger entries", id: "list" },
              { type: "p", text: "Returns all entries for your tenant in a date range, newest first." },
              { type: "code", lang: "bash", code: `GET /v1/ledger?from=2026-06-01&to=2026-06-30&limit=50` },
              { type: "h2", text: "Ledger summary", id: "summary" },
              { type: "p", text: "Returns aggregated totals for a period. This is the source of your revenue dashboard numbers." },
              { type: "code", lang: "bash", code: `GET /v1/ledger/summary?from=2026-06-01&to=2026-06-30` },
              { type: "code", lang: "json", code: `{\n  "data": {\n    "total_charged": 91500000,\n    "total_refunded": 500000,\n    "net_revenue": 91000000,\n    "entry_count": 44,\n    "currency": "NGN"\n  }\n}` },
            ],
          },
          {
            id: "ref-finance",
            label: "Finance & metrics",
            icon: "ti-chart-bar",
            blocks: [
              { type: "p", text: "Finance endpoints compute business metrics from the ledger. They are read-only and always derived from immutable historical data." },
              { type: "table", headers: ["Endpoint", "What it returns", "Key field"], rows: [
                ["GET /v1/finance/mrr", "Monthly recurring revenue for a given period", "mrr_kobo"],
                ["GET /v1/finance/arr", "Annualised recurring revenue (MRR × 12)", "arr_kobo"],
                ["GET /v1/finance/churn", "Churn rate and cancelled subscription count", "churn_rate_pct"],
                ["GET /v1/finance/dunning-recovery", "Revenue recovered through dunning retries", "recovered_kobo"],
                ["GET /v1/finance/revenue-report", "Gross, refunds, and net revenue for a period", "net_revenue"],
              ]},
              { type: "code", lang: "bash", code: `GET /v1/finance/mrr?period=2026-06\n\n{\n  "data": {\n    "mrr_kobo": 4200000,\n    "currency": "NGN",\n    "period": "2026-06"\n  }\n}` },
            ],
          },
          {
            id: "ref-webhooks",
            label: "Webhooks",
            icon: "ti-webhook",
            blocks: [
              { type: "h2", text: "Register an endpoint", id: "register" },
              { type: "code", lang: "bash", code: `POST /v1/webhooks/endpoints\n\n{\n  "url": "https://yourapp.ng/webhooks/tori",\n  "events": ["*"]  // "*" subscribes to all events\n}` },
              { type: "p", text: "The response includes a one-time `secret`. Save it — it is used to verify every delivery and is never shown again." },
              { type: "h2", text: "List endpoints", id: "list" },
              { type: "code", lang: "bash", code: `GET /v1/webhooks/endpoints` },
              { type: "h2", text: "View delivery logs", id: "logs" },
              { type: "code", lang: "bash", code: `GET /v1/webhooks/logs` },
              { type: "h2", text: "Retry a delivery", id: "retry" },
              { type: "code", lang: "bash", code: `POST /v1/webhooks/logs/{id}/retry` },
              { type: "h2", text: "Signature verification", id: "verify" },
              { type: "code", lang: "js", code: `const crypto = require('crypto');\n\nconst sig = crypto\n  .createHmac('sha256', process.env.TORI_WEBHOOK_SECRET)\n  .update(rawBody)\n  .digest('hex');\n\nconst trusted = crypto.timingSafeEqual(\n  Buffer.from(sig),\n  Buffer.from(req.headers['tori-signature'])\n);` },
              { type: "h2", text: "Retry schedule for failed deliveries", id: "retries" },
              { type: "p", text: "If your server does not return 2xx, Tori retries delivery at 5 minutes, 30 minutes, 2 hours, then 6 hours. Every attempt is logged and replayable from the dashboard." },
              { type: "callout", variant: "warn", text: "Respond 200 immediately and process asynchronously. If processing takes more than a few seconds, Tori may time out and schedule an unnecessary retry. Duplicate events are possible — make your webhook handler idempotent by checking whether you have already processed an event ID before acting on it." },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "developer-resources",
    label: "Developer Resources",
    groups: [
      {
        group: "Resources",
        items: [
          {
            id: "test-cards",
            label: "Test cards",
            icon: "ti-credit-card",
            blocks: [
              { type: "p", text: "Use these card outcomes in the sandbox to exercise every billing scenario without real money. Each maps to a real failure classification — so you can verify your webhook handling and product logic end to end before going live." },
              { type: "table", headers: ["Scenario", "Failure code", "Classification", "Resulting state"], rows: [
                ["Successful charge", "approved", "—", "ACTIVE"],
                ["Not enough money", "insufficient_funds", "Retriable", "DUNNING"],
                ["Bank system down", "issuer_unavailable", "Retriable", "DUNNING"],
                ["Request timed out", "transaction_timeout", "Retriable", "DUNNING"],
                ["Card expired", "card_expired", "Permanent", "SUSPENDED (immediate)"],
                ["Card blocked for online", "card_blocked", "Permanent", "SUSPENDED (immediate)"],
                ["Bank declined definitively", "do_not_honour", "Permanent", "SUSPENDED (immediate)"],
              ]},
              { type: "callout", variant: "info", text: "Try this sequence: start a subscription with an insufficient_funds card so it enters DUNNING. Then switch the card to approved and trigger a manual retry. Watch dunning.recovered fire and the subscription return to ACTIVE. This is the full dunning lifecycle in one test." },
            ],
          },
          {
            id: "errors",
            label: "Error codes",
            icon: "ti-alert-triangle",
            blocks: [
              { type: "p", text: "Errors always follow the same envelope with a stable machine-readable `code` and a human-readable `message`. Always branch your error handling on `code`, never on `message` — messages may change in wording, codes will not." },
              { type: "table", headers: ["HTTP status", "Error code", "What it means", "What to do"], rows: [
                ["400", "invalid_body", "The request body was not valid JSON", "Check your request body format"],
                ["400", "missing_field", "A required field was not included", "Add the missing field"],
                ["400", "invalid_amount", "The amount is zero or negative", "Send a positive integer in kobo"],
                ["401", "unauthorised", "Missing or invalid API key or JWT", "Check your credentials"],
                ["404", "not_found", "The resource does not exist for this tenant", "Check the ID is correct"],
                ["409", "email_taken", "A customer with that email already exists", "Look up the existing customer instead"],
                ["422", "invalid_transition", "The state machine rejected the action", "Check the current state allows this action"],
                ["429", "rate_limited", "Too many requests per minute", "Back off until X-Ratelimit-Reset"],
                ["500", "internal_error", "Something went wrong on Tori's side", "Retry with exponential backoff, contact support if persistent"],
              ]},
            ],
          },
          {
            id: "ratelimits",
            label: "Rate limits",
            icon: "ti-gauge",
            blocks: [
              { type: "p", text: "The API allows 100 requests per minute per IP address. Every response includes rate limit headers so you can track your usage and throttle proactively." },
              { type: "code", lang: "bash", code: `X-Ratelimit-Limit: 100        # max requests per window\nX-Ratelimit-Remaining: 73     # how many you have left\nX-Ratelimit-Reset: 1781870000 # Unix timestamp when the window resets` },
              { type: "p", text: "When you exceed the limit, you receive a 429 response. Do not retry immediately — wait until the reset timestamp before making another request." },
              { type: "callout", variant: "warn", text: "If you are bulk-creating customers or subscriptions, stagger your requests to stay under the limit. For large batch operations — importing thousands of customers at once — contact us for an elevated rate limit." },
            ],
          },
          {
            id: "idempotency",
            label: "Idempotency",
            icon: "ti-copy-check",
            blocks: [
              { type: "p", text: "Idempotency means that making the same request multiple times produces the same result as making it once. This is critical for billing — you never want to accidentally charge a customer twice or create duplicate subscriptions because a network request timed out and your server retried." },
              { type: "h2", text: "How it works", id: "how" },
              { type: "p", text: "Pass an `idempotency_key` in the request body when creating a subscription. If Tori has already processed a request with that key, it returns the original result without creating anything new. The key is tied to your tenant, so keys from different accounts never collide." },
              { type: "code", lang: "json", code: `{\n  "customer_id": "cus_...",\n  "plan_id": "plan_...",\n  "idempotency_key": "sub_user_12345_pro_2026"\n}` },
              { type: "h2", text: "Choosing a good key", id: "choosing" },
              { type: "p", text: "A good idempotency key is stable for the specific operation but unique across different operations. A common pattern is to combine your user ID with the operation type:" },
              { type: "list", items: [
                "`sub_user_12345_pro` — user 12345 subscribing to the Pro plan",
                "`sub_user_12345_pro_upgrade_2026-06` — same user upgrading in June",
                "A UUID you generate when the user clicks Subscribe, stored in your session",
              ]},
              { type: "callout", variant: "success", text: "Nigerian mobile networks drop connections regularly. Always use idempotency keys on subscription creation so a timeout followed by a retry never results in double billing." },
            ],
          },
          {
            id: "postman",
            label: "Postman collection",
            icon: "ti-package",
            blocks: [
              { type: "p", text: "The Tori Postman collection covers every endpoint with example request bodies, environment variables for your API key, and chained requests that pass IDs between steps automatically." },
              { type: "h2", text: "Getting started", id: "getting-started" },
              { type: "list", items: [
                "Import the collection into Postman",
                "Create a Tori environment with `api_key` set to your `tori_live_...` key",
                "Set `base_url` to `https://api.tori.ng`",
                "Run the Getting Started folder top to bottom — it creates a plan, customer, and subscription in sequence",
              ]},
              { type: "p", text: "The collection uses Postman's test scripts to extract IDs from responses and store them as environment variables. When you create a plan, its ID is automatically saved and used in the subscription creation request. No manual copying required." },
              { type: "callout", variant: "info", text: "The collection includes pre-request scripts that verify your API key is set and your environment is configured correctly before each request runs." },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "changelog",
    label: "Changelog",
    groups: [
      {
        group: "Releases",
        items: [
          {
            id: "changelog",
            label: "All releases",
            icon: "ti-history",
            blocks: [
              { type: "h2", text: "2026-06-20 — Public beta launch", id: "v1" },
              { type: "p", text: "The first public release of Tori, available to all businesses building on Nomba." },
              { type: "list", items: [
                "Plans with monthly, annual, and custom intervals — termly billing, quarterly retainers, any cadence",
                "Subscriptions with a fully validated seven-state lifecycle enforced by a pure state machine",
                "Nigerian-aware dunning with card failure classification — retriable vs permanent — and payday-tuned retry schedule",
                "Append-only financial ledger — every charge, refund, credit, and adjustment recorded immutably",
                "MRR, ARR, churn rate, and dunning recovery metrics computed from real ledger history",
                "HMAC-SHA256 signed, replayable webhooks covering the full billing event surface",
                "Self-service customer portal tokens for pause, resume, and cancellation without support tickets",
                "Per-IP rate limiting with budget headers on every response",
                "Idempotent subscription creation for safe retries over unreliable networks",
                "Full dashboard: subscription management, customer directory, plan builder, finance charts, webhook logs, API key management",
              ]},
              { type: "h2", text: "2026-05-15 — Private preview", id: "v0" },
              { type: "p", text: "Internal testing with a small group of Nigerian SaaS founders." },
              { type: "list", items: [
                "Core billing engine with correct month-end date clamping — January 31 + 1 month = February 28, always",
                "Proration engine for mid-cycle plan changes",
                "Initial Platform API surface — plans, customers, subscriptions",
                "Idempotency key support on subscription creation",
                "PostgreSQL-backed job queue for scheduling retry events",
              ]},
              { type: "callout", variant: "info", text: "Tori is in public beta. The API surface is stable and will not have breaking changes within the 2026-06-01 version. Feedback from early integrators directly shapes the roadmap." },
            ],
          },
        ],
      },
    ],
  },
];
