// Client-side invoice PDF generation for the customer portal — same visual
// design as the dashboard's invoice PDF (internal/../dashboard/invoices),
// adapted to the portal's DownloadInvoice response shape.

export interface DownloadableInvoice {
  invoice: {
    id: string;
    subscription_id: string;
    amount: number;
    currency: string;
    status: string;
    due_date: string;
    paid_at?: string;
    nomba_charge_ref?: string;
  };
  plan_name?: string;
  plan_interval?: string;
  merchant_name: string;
  customer_email: string;
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-NG", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString("en-NG", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

export async function downloadInvoicePDF(data: DownloadableInvoice) {
  const { jsPDF } = await import("jspdf");
  const { invoice: inv, merchant_name, customer_email, plan_name } = data;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const invShort = inv.id.slice(0, 8).toUpperCase();

  const dark: [number, number, number] = [15, 23, 40];
  const green: [number, number, number] = [0, 179, 126];
  const gray: [number, number, number] = [138, 148, 166];
  const lightGray: [number, number, number] = [248, 249, 250];

  doc.setFillColor(...dark);
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Tori", 15, 17);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...gray);
  doc.text("INVOICE", 168, 12);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text(`#${invShort}`, 168, 18);

  const isPaid = inv.status === "paid";
  doc.setFillColor(isPaid ? 227 : 238, isPaid ? 247 : 242, isPaid ? 239 : 255);
  doc.roundedRect(160, 20, 35, 6, 2, 2, "F");
  doc.setTextColor(isPaid ? 10 : 67, isPaid ? 122 : 56, isPaid ? 86 : 202);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text(inv.status.toUpperCase(), 177, 24.5, { align: "center" });

  doc.setTextColor(...dark);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  const amountStr = `NGN ${(inv.amount / 100).toLocaleString("en-NG", { minimumFractionDigits: 2 })}`;
  doc.text(amountStr, 15, 50);

  doc.setFillColor(...lightGray);
  doc.roundedRect(14, 58, 85, 28, 3, 3, "F");
  doc.roundedRect(111, 58, 85, 28, 3, 3, "F");

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...gray);
  doc.text("FROM", 20, 65);
  doc.text("TO", 117, 65);

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...dark);
  doc.text(merchant_name.slice(0, 24), 20, 72);
  doc.text((customer_email || "—").slice(0, 24), 117, 72);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...gray);
  doc.text("via Tori billing infrastructure", 20, 78);
  doc.text(plan_name ? `${plan_name} subscriber` : "Customer", 117, 78);

  let y = 98;
  const rows: [string, string][] = [
    ["Invoice ID", inv.id],
    ["Plan", plan_name ?? "—"],
    ["Currency", inv.currency],
    ["Due date", formatDate(inv.due_date)],
    ["Paid at", inv.paid_at ? formatDateTime(inv.paid_at) : "Unpaid"],
    ["Reference", inv.nomba_charge_ref ?? "—"],
  ];

  doc.setFontSize(8);
  rows.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(...lightGray);
      doc.rect(14, y - 4, 182, 8, "F");
    }
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...gray);
    doc.text(label, 18, y);
    doc.setTextColor(...dark);
    doc.text(value.slice(0, 55), 70, y);
    y += 9;
  });

  y += 6;
  doc.setFillColor(...dark);
  doc.rect(14, y, 182, 8, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("Description", 18, y + 5.5);
  doc.text("Amount", 185, y + 5.5, { align: "right" });

  y += 10;
  doc.setFillColor(...lightGray);
  doc.rect(14, y - 4, 182, 8, "F");
  doc.setTextColor(...dark);
  doc.setFont("helvetica", "normal");
  doc.text(plan_name ? `${plan_name} billing` : "Subscription billing", 18, y);
  doc.text(amountStr, 185, y, { align: "right" });

  y += 10;
  doc.setFillColor(...green);
  doc.rect(14, y - 4, 182, 9, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Total", 18, y + 1.5);
  doc.text(amountStr, 185, y + 1.5, { align: "right" });

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...gray);
  doc.text(
    `Generated by Tori · ${new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" })}`,
    105,
    285,
    { align: "center" },
  );

  doc.save(`invoice-${invShort}.pdf`);
}
